### ISSUE TITLE
FontTools is a community effort...

### ISSUE THREAD

**Issue by justvanrossum** [scribbletone/i-can-variable-font#1]
Thanks for mentioning my name with FontTools, and while I wrote a lot of the initial code, it's a true community effort these days, with major roles for @behdad, @anthrotype and @brawer. I didn't write a single line of code for varLib for example :)

**Comment by traviskochel** [comment]
@justvanrossum Sorry about that. I just changed it to `a community project with contributions by @justvanrossum, @behdad, @anthrotype, @brawer, and many more`.  

Let me know if you'd prefer it worded differently.

**Comment by justvanrossum** [comment]
That's great, thanks :)
