### ISSUE TITLE
Browser recommendation needs updating

### ISSUE THREAD

**Issue by Lorp** [scribbletone/i-can-variable-font#11]
The link for "Requires a browser that supports Variable Fonts" is currently not valid, since WebKit Nightly and Safari Tech Preview stopped supporting variable fonts on macOS (except on macOS 10.13 High Sierra beta). The best browser to link to now is [Chrome Canary](https://www.google.com/chrome/browser/canary.html), which works on multiple platforms, but users also need to enable "Experimental Web Platform Features". Feel free to link to [How to get variable fonts working in Safari, Chrome and Firefox](http://www.axis-praxis.org/blog/2017-04-05/17/how-to-get-variable-fonts-working-in-safari-chrome-and-firefox-macos), which explains the browser options.

**Comment by traviskochel** [comment]
Cool thanks for the info. Pointed the link to your site instead of safari.

FYI, it seems just enabling the flag in the latest version of Chrome(not Canary) works now.

**Comment by Lorp** [comment]
Cool, thanks.

On Canary/nonCanary, in terms of bug fixes etc., the Chrome people prefer people to be testing variable fonts using Chrome Canary, so I’m just passing that on. The great thing about it working on standard Chrome is that you can go to most computers and get variable fonts working without a big download.
