### ISSUE TITLE
THANK YOU.

### ISSUE THREAD

**Issue by shannpersand** [scribbletone/i-can-variable-font#14]
Hullo, thank you for making this. It's been really had to find easily understandable information about creating variable fonts, thanks for putting the time into this example. 💯 

I did have an issue installing fontmake where I had to [re-install pip](https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies-th/49748494#49748494) because of TSLv1.0/1.1 pip issues that took effect in April, it's a little obscure for the readme, but just wanted to mention in case anyone else has this issue.

Mostly this isn't an official `issue` just wanted to say thanks!

**Comment by traviskochel** [comment]
Cool, glad you found it helpful! And thanks for the info about reinstalling.
