### ISSUE TITLE
Mention pre-compiled binaries for fontview

### ISSUE THREAD

**Issue by brawer** [scribbletone/i-can-variable-font#3]
The README says: “Mac previewer (requires running a script to build the application)”. Actually, if you want, you also just take the [pre-compiled binary](https://github.com/googlei18n/fontview/releases). When using the app for the first time, use the right mouse button (or control-click) to confirm that you’re ok with opening an app downloaded from the Internet.

**Comment by traviskochel** [comment]
Aha! I thought I was missing something. Much easier!
