### ISSUE TITLE
Superpolator rules

### ISSUE THREAD

**Issue by LettError** [scribbletone/i-can-variable-font#6]
> Superpolator substitution rules (http://new.superpolator.com/documentation/rules/) get lost somewhere between the designspace file and the generated v-font. Or perhaps the generated fonts are legit and the apps that currently support v-fonts just don't support that feature yet?

The rules do get lost at the moment. I need to add them to the designspace export, and then they need to be supported by varlib. FWIW, this feature is not yet fully supported in the FDK feature language either. I'm sure that will happen.

**Comment by traviskochel** [comment]
Thanks for the clarification. cc @nicksherman
