### ISSUE TITLE
Calling varLib

### ISSUE THREAD

**Issue by behdad** [scribbletone/i-can-variable-font#9]
Heya,

Recent versions of fonttools ship with a shell command called "fonttools".  Instead of invoking `python fonttools/Lib/fontTools/varLib/__init__.py my.designspace` you can now just say `fonttools varLib my.designspace`

**Comment by traviskochel** [comment]
Cool. What version did that change, just so I can make a note of that in there?

**Comment by anthrotype** [comment]
Since 3.2.0

**Comment by traviskochel** [comment]
thanks!
